apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bzgg1d6u4-python 
  janus-idp.io/tekton: bzgg1d6u4-python
  backstage.io/kubernetes-id: bzgg1d6u4-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bzgg1d6u4-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml